### ISSUE TITLE
[Bug]: Cannot Remove Default Ingredients/Outputs and Add Only Custom Entries

### ISSUE THREAD

**Issue by Darkosto** [Mrbysco/ThisMatters#5]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.1.79 (NeoForge)

### Minecraft version

1.20.1

### Mod version

2.0.1

### Java version

Java 17.0.6

### Issue Description

Altering the json files via a datapack does not completely remove the default inputs or outputs: 
![image](https://github.com/Mrbysco/ThisMatters/assets/10309699/f3d54bbf-135a-4daa-b08e-1772a63dcf12)

I have used the same files provided in the jar datapack and listed my own custom ingredients: 
![image](https://github.com/Mrbysco/ThisMatters/assets/10309699/557430da-6a4c-47af-a401-9938801bb8af)

The mod does not allow the default ingredients to be removed so I cannot have a fully custom ingredients and outputs. Is there a way to remove all default entries and only allow my custom entries to be used?

### Additional Information

I turned it off and back on again and it still didn't work.

**Comment by Mrbysco** [comment]
The 2_matter recipe by default has the forge:dyes tag.
I've added a config option so you can disable the built-in checks in 2.1.0
